sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip setuptools
  - pip install tox-travis
script:
  - tox
  - git diff-tree --no-commit-id --name-only -r $REVISION | xargs pre-commit run --files
